Update CI/CD pipeline to rename Docker image and container for consistency

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -34,7 +34,7 @@ jobs:
         with:
           context: .
           push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/btn-backend:latest
+          tags: ${{ secrets.DOCKER_USERNAME }}/andreas-backend:latest
 
       # Step 7: Setup SSH for EC2
       - name: Setup SSH for EC2
@@ -61,15 +61,16 @@ jobs:
             fi
             
             echo 'Pulling Docker image...'
-            docker pull ${{ secrets.DOCKER_USERNAME }}/btn-backend:latest || { echo 'Docker pull failed'; exit 1; }
+            docker pull ${{ secrets.DOCKER_USERNAME }}/andreas-backend:latest || { echo 'Docker pull failed'; exit 1; }
     
             echo 'Stopping existing container...'
-            docker stop btn-backend || true 
-            docker rm btn-backend || true
+            docker stop andreas-backend || true 
+            docker rm andreas-backend || true
     
             echo 'Running new container...'
-            docker run -d -p 8000:8000 --name btn-backend \
+            docker run -d -p 8000:8000 --name andreas-backend \
               -e MONGO_URL='${{ secrets.MONGO_URL }}' \
+              -e PORT='${{ secrets.PORT }}' \
               -e NEXT_PUBLIC_APP_URL='${{ secrets.NEXT_PUBLIC_APP_URL }}' \
               -e RESEND_API_KEY='${{ secrets.RESEND_API_KEY }}' \
               -e COMPANY_RESEND_GMAIL_ACCOUNT='${{ secrets.COMPANY_RESEND_GMAIL_ACCOUNT }}' \
@@ -82,7 +83,7 @@ jobs:
               -e AWS_REGION='${{ secrets.AWS_REGION }}' \
               -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
               -e AWS_BUCKET_NAME='${{ secrets.AWS_BUCKET_NAME }}' \
-              ${{ secrets.DOCKER_USERNAME }}/btn-backend:latest || { echo 'Docker run failed'; exit 1; }
+              ${{ secrets.DOCKER_USERNAME }}/andreas-backend:latest || { echo 'Docker run failed'; exit 1; }
 
             echo 'Container running successfully'
     
